### ISSUE TITLE
Can't shortern link

### ISSUE THREAD

**Issue by AchoArnold** [dbkaplun/hipshort#1]
I got the following error

![image](https://lh3.googleusercontent.com/mjSOL4pnQfn4XsAcCbpbSGApSIct8JF07_xkDz9wTerZA2x9bRfddGXOnycuZPCDR0rNuhYG0ELXW1tGQ_9hWHs=s846)

**Comment by dbkaplun** [comment]
Hmm, that's odd. Works fine on OSX 10.10 with Chrome 42 as well as Firefox 37. Have you tried any other browsers?

When I try to shorten http://www.reddit.com/r/wtf/comments/35rqtc/abortion_homosexuality_and_parenting, I get http://hip.sh/food-truck-roof-party.

**Comment by AchoArnold** [comment]
Yep. I tried Firefox on ubuntu and  I had the same issue.  I've also tried on chrome on android. I couldn't still shorten a link

**Comment by dbkaplun** [comment]
Interesting. When you hit this URL, what does it say under "Try it out"? https://www.websocket.org/echo.html

**Comment by AchoArnold** [comment]
I get the statement saying **"This browser supports WebSocket."**

**Comment by AchoArnold** [comment]
Ahhhh @secrettriangle The site works perfectly today :)

**Comment by dbkaplun** [comment]
Awesome! Closing.
